spring:
  thymeleaf:
    cache: false
    prefix: file:dynamic-board-web/src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
  datasource:
    url: jdbc:mysql://localhost:3306/develop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # username: root
    # password: 1234
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK